version: "3.1"
nlu:
- intent: bot_challenge
  examples: |
    - तू बॉट आहेस का?
    - मी माणसाशी बोलतोय का?
    - मी बॉटशी बोलत आहे का?
- intent: goodbye
  examples: |
    - बाय
    - निरोप
    - पुन्हा भेटू
    - शुभ रात्री
- intent: affirm
  examples: |
    - बरोबर
    - खरोखर
    - हो
    - ते चांगले वाटते
- intent: deny
  examples: |
    - ते आवडत नाही
    - मला नाही वाटत
    - नाही
    - कधीही
- intent: q2
  examples: |
    - महाराष्ट्र जमीन महसूल संहिता १९६६ कधी लागू झाला ते वर्ष सांगू शकाल?
    - महाराष्ट्र जमीन महसूल संहिता १९६६ कोणत्या वर्षी लागू करण्यात आली?
    - १९६६ चा महाराष्ट्र जमीन महसूल संहिता कोणत्या वर्षी कायदा बनला?
    - १९६६ च्या महाराष्ट्र जमीन महसूल संहिता लागू करण्याचे वर्ष कोणते होते? कोणत्या वर्षी महाराष्ट्र जमीन महसूल संहिता, १९६६ लागू करण्यात आली?
- intent: q1
  examples: |
    - सरकारी नियमनाचे नाव काय आहे?
    - नमूद केलेल्या कायद्याचे शीर्षक काय आहे?
    - या सामग्रीमध्ये चर्चा केलेल्या सरकारी कायद्याचे नाव तुम्ही ठरवू शकता?
    - नमूद केलेल्या सरकारी कायद्याचे शीर्षक काय आहे?
    - तुम्ही कायद्याचे नाव देऊ शकता का?
- intent: q3
  examples: |
    - कायद्यात शेवटची दुरुस्ती कधी झाली?
    - कायद्यात शेवटचा बदल केव्हा झाला?
    - कायद्यात सर्वात अलीकडील बदल केव्हा करण्यात आला?
    - कायद्याच्या शेवटच्या अपडेटची तारीख काय आहे?
- intent: q4
  examples: |
    - देशात कायदा छापण्याची जबाबदारी कोणाची?
    - भारतात कायदा छापण्यासाठी जबाबदार असलेली संस्था ओळखू शकता का?
    - भारतात कायदा छापण्यासाठी कोणते प्राधिकरण जबाबदार आहे?
    - भारतात या कायद्याचा अधिकृत मुद्रक कोण आहे?
    - भारतात कायदा छापण्याची जबाबदारी कोणाची?
- intent: q5
  examples: |
    - महाराष्ट्रातील शासकीय मुद्रण, लेखनसामग्री आणि प्रकाशनांसाठी सध्याच्या संचालकाचे नाव देऊ शकता का?
    - सध्या महाराष्ट्रातील शासकीय मुद्रण, लेखनसामग्री आणि प्रकाशनांसाठी संचालक म्हणून कोण कार्यरत आहे?
    - सध्या महाराष्ट्रातील शासकीय मुद्रण, लेखनसामग्री आणि प्रकाशनांसाठी संचालक म्हणून कोणाची भूमिका आहे?
    - महाराष्ट्र राज्यातील शासकीय मुद्रण, लेखनसामग्री आणि प्रकाशन संचालक कोण आहेत?
    - महाराष्ट्र राज्यातील शासकीय मुद्रण, लेखनसामग्री आणि प्रकाशनांचे वर्तमान संचालक कोण आहेत?
- intent: q6
  examples: |
    - कायद्याची छापील प्रत खरेदी करणे किती महाग आहे?
    - कायद्याची हार्ड कॉपी मिळविण्याची किंमत काय आहे?
    - कायद्याची भौतिक प्रत मिळविण्याशी संबंधित खर्च काय आहे?
    - कायद्याच्या छापील आवृत्तीची किंमत किती आहे?
    - नमूद केलेल्या कायद्याच्या छापील प्रतीची किंमत किती आहे?
- intent: q7
  examples: |
    - तुम्ही सरकारी सेंट्रल प्रेसचे ठिकाण तपशील देऊ शकता का?
    - सरकारी केंद्रीय मुद्रणालयचा ठावठिकाणा सांगू शकाल का?
    - सरकारी सेंट्रल मुद्रणालयचा पत्ता काय आहे?
    - सरकारी सेंट्रल प्रेसचे भौतिक स्थान काय आहे?
    - सरकारी केंद्रीय मुद्रणालय कुठे मिळेल?
- intent: q8
  examples: |
    - १९६६ च्या महाराष्ट्र अधिनियम क्रमांक XLI ची विभागीय संलग्नता काय आहे?
    - १९६६ चा महाराष्ट्र अधिनियम क्रमांक XLI कोणत्या विभागांतर्गत कार्यरत आहे?
    - १९६६ चा महाराष्ट्र अधिनियम क्रमांक XLI कोणत्या विभागांतर्गत येतो?
    - १९६६ चा महाराष्ट्र अधिनियम क्रमांक XLI कोणत्या विभागात येतो?
- intent: q9
  examples: |
    - १९६६ पासून महाराष्ट्र जमीन महसूल संहितेचे प्राथमिक उद्दिष्ट काय आहे?
    - १९६६ मध्ये महाराष्ट्र जमीन महसूल संहिता तयार करण्यामागील मुख्य उद्देश काय होता?
    - १९६६ चा महाराष्ट्र जमीन महसूल संहिता कोणत्या कारणासाठी लागू करण्यात आला?
    - १९६६ मध्ये महाराष्ट्र जमीन महसूल संहिता लागू करण्याचा उद्देश काय आहे?
    - १९६६ मध्ये महाराष्ट्र जमीन महसूल संहिता लागू करण्यामागील हेतू काय होता?
- intent: q10
  examples: |
    - व्यक्तींना त्यांच्या संदर्भ गरजांसाठी कायद्याची प्रत कशी उपलब्ध आहे?
    - व्यक्तींना त्यांच्या अभ्यासासाठी कायद्याची प्रत मिळविण्यासाठी कोणते पर्याय उपलब्ध आहेत?
    - कोणकोणत्या मार्गांनी व्यक्ती संदर्भित करण्यासाठी कायद्याची प्रत मिळवू शकतात?
    - संदर्भासाठी कायद्याची प्रत मिळविण्यासाठी व्यक्तींसाठी कोणत्या पद्धती उपलब्ध आहेत?
    - व्यक्ती त्यांच्या संदर्भ हेतूंसाठी कायद्याची प्रत कशी मिळवू शकतात?
- intent: q11
  examples: |
    - महाराष्ट्र जमीन महसूल संहिता, १९६६, राज्याचे महसुली क्षेत्रांमध्ये विभाजन करण्याच्या प्रक्रियेची रूपरेषा कशी देते?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ नुसार, राज्याची महसुली क्षेत्रात कशी विभागणी केली जाते?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ नुसार, राज्यातील महसूल क्षेत्र कसे रेखाटले जातात?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ नुसार महसूल क्षेत्रात राज्याचे विभाजन करण्याची पद्धत काय आहे?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ मध्ये नमूद केल्यानुसार महसूल क्षेत्रात राज्याचे विभाजन करण्यासाठी कोणते निकष वापरले जातात?
- intent: q12
  examples: |
    - महसूल अधिकाऱ्यांवर कोणती जबाबदारी आणि अधिकारी आहेत?
    - महसूल अधिकाऱ्यांना नेमून दिलेले विशिष्ट अधिकार आणि कर्तव्ये कोणती आहेत?
    - महसूल अधिकाऱ्यांचे अधिकार आणि जबाबदाऱ्या तुम्ही सविस्तर सांगू शकाल का?
    - महसूल अधिकाऱ्यांचे अधिकार आणि कर्तव्ये सांगा.
    - महसूल अधिकाऱ्यांचे अधिकार आणि कर्तव्ये काय आहेत?
- intent: q13
  examples: |
    - कोड अंतर्गत सार्वजनिक पैसे वसूल करण्यासाठी विहित प्रक्रिया काय आहेत?
    - सार्वजनिक पैसे वसूल करण्याची प्रक्रिया कोडमध्ये कशी नमूद केली जाते?
    - सार्वजनिक निधीच्या पुनर्प्राप्तीसाठी कोडमध्ये कोणत्या पद्धती दर्शविल्या आहेत?
    - संहितेनुसार, सार्वजनिक निधी वसूल करण्यासाठी कोणती पावले उचलली जातात?
- intent: q14
  examples: |
    - संहितेत नमूद केल्याप्रमाणे सर्व जमिनी, सार्वजनिक रस्ते इत्यादींमध्ये राज्याचे शीर्षक काय आहे?
    - संहितेनुसार, सर्व जमिनी आणि सार्वजनिक रस्त्यांबाबत राज्याचे शीर्षक काय आहे?
    - संहितेमध्ये नमूद केल्याप्रमाणे सर्व जमिनी आणि सार्वजनिक रस्त्यांच्या संदर्भात राज्य औपचारिकपणे कसे नियुक्त केले जाते?
    - संहितेत नमूद केल्याप्रमाणे सर्व जमिनी आणि सार्वजनिक रस्त्यांच्या संदर्भात राज्याचे कोणते शीर्षक आहे?
    - संहितेनुसार सर्व जमिनी आणि सार्वजनिक रस्त्यांबाबत राज्याची कायदेशीर स्थिती काय आहे?
- intent: q15
  examples: |
    - तुरुंगात असलेल्या अधिकारी किंवा व्यक्तीसाठी कोड अंतर्गत त्यांची सुटका सुरक्षित करण्यासाठी कोणत्या पद्धती उपलब्ध आहेत?
    - तुरुंगातील अधिकारी किंवा व्यक्ती संहितेनुसार त्यांची सुटका कशी करू शकते?
    - तुरुंगात असलेल्या अधिकारी किंवा व्यक्तीला त्यांची सुटका करण्यासाठी कोणती प्रक्रिया उपलब्ध आहे?
    - तुरुंगातील अधिकारी किंवा व्यक्तीची सुटका करण्यासाठी विहित प्रक्रिया काय आहेत?
    - तुरुंगातील अधिकारी किंवा व्यक्तीला त्यांची सुटका करण्यासाठी कोणते पर्याय आहेत?
- intent: q16
  examples: |
    - विशिष्ट हेतूंसाठी जमिनीच्या असाइनमेंटसाठी कोड कोणती प्रक्रिया स्थापित करते?
    - विशेष उद्देशांसाठी जमिनींचे वाटप करण्याची प्रक्रिया कोडमध्ये कशी नमूद केली जाते?
    - संहितेनुसार विशेष कारणांसाठी जमिनी देण्याची प्रक्रिया काय आहे?
    - संहितेनुसार, विशिष्ट हेतूंसाठी जमिनी नियुक्त करण्याचा प्रोटोकॉल काय आहे?
    - संहिता विशिष्ट उद्देशांसाठी जमिनींचे वाटप करण्याच्या प्रक्रियेची रूपरेषा कशी दर्शवते?
- intent: q17
  examples: |
    - संहितेच्या तरतुदींनुसार संबंधित व्यक्तीला पैसे, कागदपत्रे इत्यादी मागण्या कशा कळवल्या जातात?
    - संहिता संबंधित व्यक्तीला पैसे, कागदपत्रे इत्यादी विनंत्यांचे संप्रेषण कसे ठरवते?
    - संहितेनुसार, प्रश्नात असलेल्या व्यक्तीला पैसे, कागदपत्रे इत्यादी विनंत्या पाठवण्यासाठी कोणती पद्धत वापरली जाते?
    - संहितेच्या अंतर्गत संबंधित व्यक्तीला पैसे, कागदपत्रे इत्यादी मागण्या कशा कळवल्या जातात?
    - संहितेनुसार पैसे, कागदपत्रे इत्यादींच्या विनंत्यांबद्दल व्यक्तींना सूचित करण्याचे विहित माध्यम कोणते आहेत?
- intent: q18
  examples: |
    - संहितेत नमूद केल्यानुसार सर्वेक्षण अधिकारी आणि मंडळ अधिकारी यांची नियुक्त कामे कोणती आहेत?
    - सर्वेक्षण अधिकारी आणि मंडळ अधिकारी संहितेनुसार कोणती कामे करतात?
    - संहिता सर्वेक्षण अधिकारी आणि मंडळ अधिकारी यांच्या भूमिका आणि जबाबदाऱ्या कशा स्पष्ट करते?
    - संहितेच्या तरतुदींनुसार सर्वेक्षण अधिकारी आणि मंडळ अधिकारी यांना कोणती कर्तव्ये नियुक्त केली जातात?
- intent: q19
  examples: |
    - संहितेनुसार, गैर-सरकारी व्यक्तींना महसूल अधिकारी अधिकार राज्य सरकारद्वारे अधिकृत करण्यामध्ये कोणते पाऊल समाविष्ट आहे?
    - संहितेच्या तरतुदींनुसार राज्य सरकार महसूल अधिकारी जबाबदाऱ्यांसह बाह्य संस्थांना कसे सक्षम करू शकते?
    - राज्य सरकार संहितेनुसार महसूल अधिकाऱ्यांचे अधिकार इतर व्यक्तींना कसे देऊ शकते?
    - राज्य सरकारद्वारे इतर व्यक्तींना महसूल अधिकारी अधिकार देण्याची प्रक्रिया संहिता कशी निर्दिष्ट करते?
    - महसूल अधिकारी अधिकार इतर पक्षांना हस्तांतरित करण्यासाठी राज्य सरकारच्या संहितेत कोणती यंत्रणा स्थापित केली आहे?
- intent: q20
  examples: |
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ कुरणाच्या जमिनींचे व्यवस्थापन आणि वापर कसा करते?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ मध्ये कुरण क्षेत्राच्या वापराबाबत कोणते नियम स्थापित केले आहेत?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ नुसार कुरणाच्या वापराबाबत काय नियम आहेत?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ नुसार, कुरण जमिनीच्या वापरावर कोणते नियम आहेत?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ कुरणाच्या वापराचे नियमन कसे करते?
- intent: q21
  examples: |
    - विशिष्ट जमिनींमधून बेकायदेशीरपणे काढलेल्या नैसर्गिक उत्पादनांचे मूल्य वसूल करण्यासाठी संहिता काय उपाय सुचवते?
    - संहितेनुसार, विनिर्दिष्ट जमिनींमधून परवानगी न घेता काढलेल्या नैसर्गिक उत्पादनांचे मूल्य वसूल करण्यासाठी कोणती कारवाई केली जाऊ शकते?
    - विशिष्ट जमिनींकडून परवानगी न घेता घेतलेल्या नैसर्गिक उत्पादनांच्या मूल्याची परतफेड करण्यासाठी संहितेत कोणत्या तरतुदींचा समावेश आहे?
    - नियुक्त केलेल्या जमिनींमधून बेकायदेशीरपणे घेतलेल्या नैसर्गिक उत्पादनांची भरपाई करण्याच्या मुद्द्याला संहिता कशी संबोधित करते?
    - नियुक्त केलेल्या जमिनींमधून बेकायदेशीरपणे काढलेल्या नैसर्गिक उत्पादनांच्या मूल्याच्या पुनर्प्राप्तीशी संहिता कशी हाताळते?
- intent: q22
  examples: |
    - वैयक्तिक होल्डिंगवरील झाडांच्या मालकीबाबत संहितेत कोणत्या तरतुदींचा समावेश आहे?
    - संहिता त्यांच्या जमिनीवरील झाडांसंबंधी व्यक्तींच्या हक्कांचे नियमन कसे करते?
    - संहिता त्यांच्या मालकीच्या झाडांबाबत व्यक्तींचे अधिकार कसे परिभाषित करते?
    - व्यक्तींना त्यांच्या होल्डिंगवर असलेल्या झाडांबद्दल कोणते अधिकार आहेत?
    - त्यांच्या जमिनीवरील झाडांबाबत व्यक्तींचे काय अधिकार आहेत?
- intent: q23
  examples: |
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ नुसार झाडे आणि जंगले सरकारच्या मालकीमध्ये कशी हस्तांतरित केली जातात?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ मध्ये झाडे आणि जंगले सरकारी मालकीकडे हस्तांतरित करण्याबाबत कोणत्या तरतुदी आहेत?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६, सरकारमधील झाडे आणि जंगले यांच्या निबंधाला कसे संबोधित करते?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ नुसार झाडे आणि जंगले सरकारकडे कशी निहित आहेत?
- intent: q24
  examples: |
    - महाराष्ट्र जमीन महसूल संहिता, १९६६, लाकूड आणि संबंधित सामग्रीचे नियंत्रण आणि वितरण कसे संबोधित करते?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ नुसार, लाकूड आणि इतर साहित्य कापण्याचे आणि पुरवठ्याचे नियमन कसे केले जाते?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ मध्ये लाकूड तोडणे आणि पुरवठा करणे इत्यादींच्या नियमनासाठी कोणत्या कार्यपद्धती नमूद केल्या आहेत?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ द्वारे लाकूड कापण्यासाठी आणि पुरवठा करण्यासाठी विहित केलेल्या नियामक उपाय काय आहेत?
    - संहितेत सांगितल्याप्रमाणे लाकूड, इत्यादी कापणे आणि पुरवठ्याचे नियमन करण्याची प्रक्रिया काय आहे?
- intent: q25
  examples: |
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ नुसार, जमीन धारण करणाऱ्या व्यक्तींच्या श्रेणी काय आहेत?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ नुसार, जमीन धारण करणाऱ्या लोकांचे परिभाषित गट कोणते आहेत?
    - संहितेनुसार जमीन धारण करणाऱ्या व्यक्तींचे वर्ग कोणते आहेत?
    - संहिता जमिनीच्या मालकीच्या आधारावर व्यक्तींचे वर्गीकरण कसे करते?
    - संहिता जमीन असलेल्या व्यक्तींचे वर्गीकरण कसे करते?
- intent: q26
  examples: |
    - संहिता त्याच्या तरतुदींनुसार मंजूर केलेल्या अलिप्त जमिनीच्या वहिवाटीचे नियमन कसे करते?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ नुसार, त्याच्या तरतुदींच्या अन्वये मंजूर करण्यात आलेल्या अलिप्त जमिनीच्या वह्याबाबत कोणत्या अटी आहेत?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६, त्याच्या तरतुदींच्या अन्वये दिलेल्या विनापरवाना जमिनीचा ताबा घेण्याबाबत कोणती उपाययोजना करते?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ मध्ये त्याच्या तरतुदींनुसार मंजूर केलेल्या अलिप्त जमिनीच्या वहिवाटीसाठी कोणत्या कार्यपद्धती नमूद केल्या आहेत?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६, त्याच्या तरतुदींच्या अन्वये दिलेल्या बेलगाम जमिनीचा व्यवस्था कसा हाताळतो?
- intent: q27
  examples: |
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ नुसार अनुदानासाठी पात्र ठरण्यासाठी बेकार जमिनीसाठी कोणते निकष पूर्ण करणे आवश्यक आहे?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ अंतर्गत बिनव्याप्त जमीन मंजूर करण्यासाठी कोणत्या पूर्व शर्ती आहेत?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६, बिनव्याप्त जमीन मंजूर करण्यासाठी पात्रता निकष कसे परिभाषित करते?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ नुसार बिनव्याप्त जमीन मंजूर करण्यासाठी कोणत्या अटी पूर्ण केल्या पाहिजेत?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ मध्ये बेकार जमीन अनुदानासाठी पात्र होण्यासाठी कोणत्या आवश्यकता नमूद केल्या आहेत?
- intent: q28
  examples: |
    - महाराष्ट्र जमीन महसूल संहिता, १९६६, अल्प प्रमाणात गाळाच्या जमिनींच्या तात्पुरत्या अधिकाराबाबत काय नमूद करते?
    - अल्प प्रमाणात गाळ असलेल्या जमिनींचा तात्पुरता अधिकार काय आहे?
    - अल्प प्रमाणात गाळ असलेल्या जमिनींच्या तात्पुरत्या अधिकारासाठी कोणत्या तरतुदी केल्या आहेत?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ अंतर्गत लहान आकाराच्या गाळाच्या जमिनीच्या तात्पुरत्या वापराबाबत काय नियम आहेत?
- intent: q29
  examples: |
    - संहितेनुसार अकृषिक कारणांसाठी परवानगीशिवाय जमीन वापरल्यास कोणते दंड आहेत?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ मध्ये नमूद केल्यानुसार जमिनीच्या अनधिकृत बिगरशेती वापरासाठी कायदेशीर परिणाम काय आहेत?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ नुसार, अकृषिक कामांसाठी परवानगीशिवाय जमिनीचा वापर केल्यास कोणते दंड लागू होतात?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ मध्ये जमिनीच्या अनधिकृत बिगरशेती वापराचे काय परिणाम आहेत?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६, अकृषिक कारणांसाठी परवानगीशिवाय जमीन वापरल्याबद्दल दंडाच्या समस्येचे निराकरण कसे करते?
- intent: q30
  examples: |
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ चे मुख्य लक्ष काय आहे?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ मध्ये संबोधित केलेली मध्यवर्ती थीम किंवा विषय काय आहे?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ मध्ये व्याजाची मुख्य क्षेत्रे कोणती आहेत?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ प्रामुख्याने कशाशी संबंधित आहे?
    - महाराष्ट्र जमीन महसूल संहिता, १९६६ चे प्रमुख उद्दिष्टे काय आहेत?
- intent: greet
  examples: |
    - शुभ दुपारी
    - अहो तिथे
    - नमस्कार भाऊ
    - शुभ सकाळ
    - चल जाऊया
    - शुभ संध्या
